version: '3'

services:
  nuxt:
    image: codershisho/node:18.18.0-alpine
    container_name: node-${PROJECT_NAME}
    tty: true
    environment:
      PORT: 3000
      HOST: 0.0.0.0
      TZ: ${TIME_ZONE}
    ports:
      - ${NODE_PORT}:3000
      - 24678:24678 # HMR用のポートを追加
    volumes:
      - ${NOTE_MOUNT_FOLDER}:/app
      - ${NOTE_MOUNT_FOLDER}/node_modules:/app/node_modules
    stdin_open: true
    restart: always
    working_dir: /app

  laravel:
    image: codershisho/php:8.2-fpm
    container_name: php-${PROJECT_NAME}
    tty: true
    ports:
      - ${PHP_PORT}:8000
    volumes:
      - ${PHP_MOUNT_FOLDER}:/var/www/html
    stdin_open: true
    restart: always
    environment:
      TZ: ${TIME_ZONE}
    working_dir: /var/www/html
    command: php artisan serve --host=0.0.0.0

  db:
    image: mariadb:10.9
    container_name: mariadb-${PROJECT_NAME}
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
    restart: always
    environment:
      TZ: ${TIME_ZONE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_DATABASE}
volumes:
  db_data:
